name: default-workflow
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "First action"
        run: echo "Hello, World!"
      - name: "Second action"
        run: |
          echo "Don't worry, be happy!"
          echo "Bye bye!"
      - name: "Python Script"
        run: |
          variavel = "Hello, Python!"
          print(variavel)
        shell: python
  second-job:
    name: "Installation of nodejs environment"
    runs-on: ubuntu-latest
    steps: 
      - name: "Current NodeJS version verification"
        run: node --version
      - name: "Defining node version v24.0.0 of NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 'v24.0.0'
      - name: "NodeJS version after update"
        run: node --version
          
